---
- hosts: all
  pre_tasks:
    - name: Wait for apt to finish
      raw: sleep 15
  roles:
    - common

- hosts: openimis
  roles:
    - role: openimis
      tags: [openimis_deployment]

- hosts: hcwathome
  roles:
    - role: hcwathome
      tags: [hcwathome_deployment]

- hosts: integration
  roles:
    - role: integration
      tags: [integration_deployment]

- hosts: ozone
  roles:
    - role: ozone
      tags: [ozone_deployment]
