---
- name: Clone the repository
  git:
    repo: https://github.com/bolaji3009/ozone.git
    dest: /home/hello/ozone
    version: main

- name: Start the hcwathome services
  shell: "docker compose up -d"
  args:
    chdir: /home/hello/ozone
