---
openimis_path: /home/hello/openimis-dist
openimis_env_vars:
  DB_PASSWORD: "mysecretpassword"
  DB_NAME: "openimis"
  DB_USER: "openimis"
  DB_HOST: "db"
  DB_PORT: "5432"
  SECRET_KEY: "mysecretkey"
  DOMAIN: "localhost"
  DEMO_DATASET: "true"
  OPENSEARCH_PASSWORD: "mysecretpassword"
  OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
  OPENSEARCH_ADMIN: "admin"
  CACHE_BACKEND: "django_redis.cache.RedisCache"
  CACHE_URL: "redis://redis:6379/1"
  CACHE_OPTIONS: ""
  REDIS_PASSWORD: ""
  HOSTS: "localhost,127.0.0.1"
  OPENIMIS_FE_CONF_JSON: "{}"
  OPENSEARCH_BASIC_TOKEN: ""
