---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'

- name: Install gsutil
  apt:
    name: google-cloud-sdk
    state: present
