---
- name: Install prerequisite packages
  apt:
    name:
      - docker.io
      - apt-transport-https
      - python3-pip
      - python3-docker
      - python3-docker-compose
    state: present
    update_cache: yes

- name: Install Docker Compose binary
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'

- name: Add Google Cloud SDK apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Google Cloud SDK repository
  apt_repository:
    repo: deb https://packages.cloud.google.com/apt cloud-sdk main
    state: present
    update_cache: yes

- name: Install gsutil
  apt:
    name: google-cloud-sdk
    state: present
