---
- name: Clone the repository
  git:
    repo: https://github.com/bolaji3009/ozone.git
    dest: /home/hello/ozone
    version: main

- name: Deploy integration services using shell
  become: true
  shell:
    cmd: "docker compose up -d rabbitmq imis-connect superset-db superset"
    chdir: "/home/hello/ozone"
